### ISSUE TITLE
Scrutiny not running daily cron job

### ISSUE THREAD

**Issue by VladFlorinIlie** [truenas/apps#1132]
Hello,

It seems that the daily cron job integrated in the Scrutiny omnibus image does not run.
My theory is that this problem could be related to the capabilities: [Similar Problem](https://stackoverflow.com/questions/70291972/cron-not-running-in-a-docker-container-with-no-capabilities)

**Comment by rsteckler** [comment]
Exactly as above, the omni-container is not running cron.  I also believe it's a combination of needed CAP_SETGID
, DAC_OVERRIDE, and CAP_SETUID that need to be added.  Here's some troubleshooting steps to execute in the container shell (change the shell from /bin/sh to /bin/bash when asked)

1.  You'll want to install some apt packages, so add the root user to the apt permissions:
```
cat <<EOF > /etc/apt/apt.conf.d/sandbox-disable
APT::Sandbox::User "root";
EOF
```

2. run ```apt update```

3. We want to see some logs, so install rsyslog: ```apt install rsyslog``` and start the daemon with ```rsyslogd```.  You'll get some errors but you can ignore them.  Now you have a /syslog file.

4. Install vi so we can edit files with ```apt install vim-tiny```

5. Adjust the logging for cron with ```vi /etc/default/cron```.  Uncomment the last line and make it say: ```EXTRA_OPTS="-L 15"``` so we have verbose cron logging to /var/log/syslog and /var/log/cron.log

6.  We need to restart the cron service with ```service cron restart```.  

7.  At this point we have a new cron service running, but it can't get the lock file because the container has an instance of cron running under the supervisor.  We need to kill that version so the cron service can grab the lock file.  We'll ```ps -AF | grep s6-supervise cron``` and note the PID.  Then we kill that process with ```kill <pid>```

8.  Now we can create a test cron job with ```crontab -e```

9.  Add a new cron job that runs every minute and tries to create a file in /tmp: ```* * * * * touch /tmp/testcron```.  Make sure to  leave an empty line after this cron job, otherwise cron won't run it.

10.  Now we can witness the permission problem with ```tail -f /var/log/cron.log```.  Wait for a minute and, amongst all of the lock file errors from having two crons running, you'll see the following:
```
CRON[2859]: (root) CMD ([2860] touch /tmp/testcron)
CRON[2860]: (CRON) error (do_command:initgroups(0) failed: Operation not permitted)
CRON[2859]: (CRON) error (grandchild #2860 failed with exit status 1)
CRON[2859]: (root) END ([2860] touch /tmp/testcron)
```

Note that it's failing, as root, when trying to access groups, hence the need as stated in the above that we need the CAP_SETGID capability for the container.  You can also ```apt install strace``` then ```strace su -``` to see a trace of su trying to change groups and failing with permission denied.

**Comment by rsteckler** [comment]
Also, presumably [this would be the spot](https://github.com/truenas/apps/blob/5d4c17f5d3568fbbf786d6d170c573d8786d1227/ix-dev/community/scrutiny/templates/docker-compose.yaml#L6) to fix it.

**Comment by stavros-k** [comment]
Thanks @rsteckler for the investigation, I wish logs wasn't that hidden, we would have seen that much earlier. Opening a PR to fix that.

**Comment by rsteckler** [comment]
Just verifying that #1146 fixed the problem and cron is running nightly now.
