### ISSUE TITLE
'Gaseous Server' reverts back to "Deploying" while background tasks run.

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/apps#1169]
'Gaseous Server' starts up normally and shows as "started"

then about an hour later one of the scheduled tasks, or "Timered events" as the log file calls it, start. This causes the container to revert back to "Deploying" while these scheduled tasks are running. Refreshing the browser cache does not change it, so it is not a glitch.

I'm not sure if anything _can_ be done about this, but I wanted to bring it up regardless.

**Comment by stavros-k** [comment]
This means that while those tasks are running the gaseous http server is unresponsive.
Which is expected to not appear as running as the healthcheck fails.

Not sure if there is something to be done there.

If there is something we can probe that does not become unresponsive while those tasks are running, please let me know!

**Comment by michael-j-green** [comment]
Hi! I'm the dev for Gaseous. I've only just become aware of the existence of the community app for Gaseous in TrueNAS.

If there is a bug here where the server is becoming unresponsive then I'd love to know - though I should point out I've not had any reports of this from users on other platforms.

@TimvanDijkNL; do you know if there is a specific timered event that this is happening with? Also; thankyou for bringing up that other issue regarding the signatures - after just having built a TrueNAS VM in order to take a look at the community app, I'm concerned that there's a lack of documentation around the application. For example, in the below screenshot there is a link to Gaseous documentation; but there is no Gaseous documentation to be found.
<img width="383" alt="Screenshot 2024-12-18 at 11 37 59 am" src="https://github.com/user-attachments/assets/ae45ebd6-6858-4b25-a8a5-060dda0c37a0" />

@stavros-k; where can I find the configuration that TrueNAS is using to build the container/app? Regarding app documentation, it can be found here: https://github.com/gaseous-project/gaseous-server/wiki. If anyone wants to contribute some TrueNAS specific installation instructions for inclusion on the project wiki, I'd be more than happy to add it.

**Comment by TimvanDijkNL** [comment]
I did some testing, started random timered events via the webUI.. none of them put the container back into "deploying". Then I uploaded 2 roms.. and about 3 minutes later: 
![image](https://github.com/user-attachments/assets/dba4efda-6925-4237-b55f-29364c09909c)
I immediately went back to the Gasseous webUI which was in fact running just fine (so not non-responsive) and no timered event seemed to be running: 
![image](https://github.com/user-attachments/assets/73b77bd1-9163-4009-a2c7-af1e1ddda6af)
So finally I copy-pasted the container log into a .txt file hopefully it gives you something to go off ?
[container log.txt](https://github.com/user-attachments/files/18181521/container.log.txt)

**Comment by kmoore134** [comment]
@michael-j-green Good to get in touch with you! I did the original App of Gaseous server, so that's probably my fault that the docs link is wrong. It should be pointing at your Wiki. I'll update that now.

**Comment by michael-j-green** [comment]
No problem at all! Thanks for taking a look at it! It looked pretty easy to set it up, so good work :)

**Comment by kmoore134** [comment]
Thanks! Great project BTW, I set it up and it's really nice! It's only been in the catalog for a short while and it already has several hundred deployments on TrueNAS, so some other folks must also be enjoying it. If you see anything else that we can fix/improve, by all means let us know or a PR is always welcome!

https://github.com/truenas/apps/tree/master/ix-dev/community/gaseous-server

Update to Notes is here:

https://github.com/truenas/apps/pull/1180

**Comment by michael-j-green** [comment]
@TimvanDijkNL; looks like your server was doing weekly maintenance at the time, which includes optimising the database tables. This can be pretty aggressive.

But if I'm reading the code for the app correctly it's querying if a static file (an image) is present to determine if the server is responding or not. I'm not sure why it's not responding during that time - I haven't been able to replicate this issue (not be able to pull the file). This makes me think that TrueNAS's health check is timing out a bit too early.

I'll keep an eye out from my end though, as delayed responses is not a good user experience, and not something I want.

**Comment by michael-j-green** [comment]
> Thanks! Great project BTW, I set it up and it's really nice! It's only been in the catalog for a short while and it already has several hundred deployments on TrueNAS, so some other folks must also be enjoying it. If you see anything else that we can fix/improve, by all means let us know or a PR is always welcome!
> 
> https://github.com/truenas/apps/tree/master/ix-dev/community/gaseous-server
> 
> Update to Notes is here:
> 
> #1180

Awesome! Thanks for the feedback! I don't do any telemetry myself so I don't know how many deployments I actually have, but it's still good to hear it's been deployed that much and users are getting value out of it.

As for the notes; looks good! But to get the most out of Gaseous, users need to download and attach the DATs to identify content. Instructions are here: https://github.com/gaseous-project/gaseous-server/wiki/Signatures

Not sure if you want to call that out or not in the notes. But yeah :)

Anyways... thanks again for your help!

**Comment by stavros-k** [comment]
Hello @michael-j-green, the timeout is 5s, and it also seems weird to me to not respond within this duration.
Querying a static file might add up if there are some heavy IO at the time and this could cause the timeout to be met.

It would be great if you could add a simple `/ping`or `/health` endpoint that just responds `200/OK`!
This might be the easiest/best solution

**Comment by michael-j-green** [comment]
This is a great idea! I'll implement it and raise a PR once it's in the release code :)

**Comment by chester40391** [comment]
I am having similar issue with the random return to deploying. I've had this issue since I installed it and it followed after several updates since. It's very frequent. I installed a fresh instance and before I had a chance to even pull up the gui it went from started to deploying in just a couple of minutes. I am going to see if I can replicat using the default install paths ".ix" but currently am installing to a dataset I created with app permissions (2 datasets actually)
