### ISSUE TITLE
Communication between app and VM

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/apps#1175]
Is there currently a way or a workaround for an app that depends on another container (e.g. database, etc.) to communicate with a VM? Or is this only possible with: https://github.com/truenas/apps/issues/583#issuecomment-2388652951
Thanks in advance.

**Comment by Spunky17** [comment]
can you clarify your statement?  are you wanting to have an app communicate with another container or to communicate with a VM?  if you want to have it communicate with another container you can create a custom yaml file and include both apps in there and have the first app be dependent on the second app (database) so that it will only start up if the database app starts up.  you can't do this natively in the TrueNAS GUI and only through a custom yanal file.  I do this for my sabnzb and transmission apps to make them dependent on my VPN app starting up.

**Comment by stavros-k** [comment]
I think you need to put the VM on the same bridge with truenas.
But will be easier when #743 lands. Follow the linked issue. Thanks
