### ISSUE TITLE
Stopped apps are started

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/apps#801]
Stopped apps are started after every update and server restart.
Generally a good thing, but I would like to be able to set which apps can be started, as is the case with docker: `no`, `on-failure`, `always`, `unless-stopped`. Or the last status should be remembered.

**Comment by stavros-k** [comment]
While the restart policy is not exposed in the apps currently, it is set to unless-stopped.
So it should stay stopped if there were stopped before.

Do you see this on non-custom apps?

**Comment by stavros-k** [comment]
I've just tested with nextcloud and it stayed stopped on reboot.
Can you list couple of apps you noticed it ?

**Comment by stavros-k** [comment]
I see, you meant app update, not server update.
On next release it wont be possible to update apps that are stopped.

https://github.com/truenas/middleware/pull/14763

This is because you cant just update the app without starting it. (Docker has to receive the changes, which will trigger the app to start)

**Comment by stavros-k** [comment]
Lets say you have a database stopped. Then you click update. Which will start the database.
and immediately stops again to return to the previous state.
This might cause corruption due to unclean shutdown.
