### ISSUE TITLE
Allow postgres app to change uid and gid

### ISSUE THREAD

**Issue by fuji44** [truenas/apps#940]
The current Postgres app uses 999 for the default UID and GID.
These overlap with the UID netdata(999) and GID docker(999) of the host OS (TrueNAS SCALE).
This is inconvenient when binding host directories.

I would like to be able to change the UID and GID as a setting just like the official App.
Also, I think another ID should be the default if possible.

**Comment by stavros-k** [comment]
Hello, see https://hub.docker.com/_/postgres/ (Section `Arbitrary --user Notes`).
It cannot really (well kinda) run as any user. Only the ones present in the `/etc/passwd` (Inside the container).

Because of that, it will not be exposed. You can however use one of the custom options (portainer, docker compose, etc)
